{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bitrix
  namespace: {{ include "bitrix.namespace" . }}
  labels:
    {{- include "bitrix.labels" . | nindent 4 }}
  annotations:
    {{- range $k, $v := .Values.ingress.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- if .Values.ingress.tls.certManager.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.certManager.clusterIssuer | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.global.domain | quote }}
      secretName: {{ .Values.ingress.tls.secretName | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.global.domain | quote }}
      http:
        paths:
          - path: /bitrix/sub/
            pathType: Prefix
            backend:
              service:
                name: bitrix-push-sub
                port:
                  number: 80
          - path: /bitrix/pub/
            pathType: Prefix
            backend:
              service:
                name: bitrix-push-pub
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bitrix-web
                port:
                  number: 80
{{- end }}
