apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.www.name }}
  namespace: {{ include "bitrix.namespace" . }}
  labels:
    {{- include "bitrix.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.pvc.www.accessMode }}
  storageClassName: {{ .Values.global.storageClass.rwx | quote }}
  resources:
    requests:
      storage: {{ .Values.pvc.www.size | quote }}
